### ISSUE TITLE
Cannot add new user to group unless new user has logged in.

### ISSUE THREAD

**Issue by elv-arun** [eluv-io/elv-fabric-browser#104]
Env: https://core.demov3.contentfabric.io/

Cannot add new user to group unless new user has logged in.

Steps to reproduce:
- Create new user
- Fund new user
- Do not log in as new user
- Add new user to a group.

Error occurs when attempting to add the user to the group. Tested a case where user logs in and then user is added and this case works as expected.
![Screen Shot 2023-12-15 at 1 37 28 PM](https://github.com/eluv-io/elv-fabric-browser/assets/63886822/d8fa6be7-2288-478a-a11c-e21101ddd5ea)

**Comment by elv-kevin** [comment]
this is not new and can't be fixed. group membership requires that the account have an associated wallet contract, which is created when the user logs in after being funded.
