### ISSUE TITLE
Failed to fetch error when trying to upload large file (> 1gb) to the fabric browser.

### ISSUE THREAD

**Issue by elv-arun** [eluv-io/elv-fabric-browser#30]
Attempting to upload a large file to the fabric browser leads to a "Failed to fetch" error.
Largest file that uploaded successfully was a 1GB file.
Error is noticed when uploading a 2GB file.

![Screen Shot 2022-02-17 at 11 57 13 AM](https://user-images.githubusercontent.com/63886822/154570435-42871869-1e6c-4df6-bdc5-81011fbc16b1.png)

**Comment by elv-gerald** [comment]
This is fixed. I tested by uploading a 4gb file to an object 
![image](https://user-images.githubusercontent.com/79117605/201433950-8b4836ee-c958-474c-b248-4343ae8f7d5a.png)
