### ISSUE TITLE
Site map (searchables)

### ISSUE THREAD

**Issue by elv-zenia** [eluv-io/elv-fabric-browser#34]
Create a new section within Asset Manager for Searchables, which are described below. 

> Clips and titles (and potentially other lists like them - series, etc) - are just list of things in the site
[11:57](https://eluvio.slack.com/archives/CF7AQGUH0/p1646078232246719)
The 'site map' (and searchables is the only thing in the site map) is intended to point to everything in the site that can be searched
[11:58](https://eluvio.slack.com/archives/CF7AQGUH0/p1646078282499639)
We used 'titles' initially for this function but that wasn't exactly right because of series, seasons and 'other videos' that are not specifically titles.
[11:59](https://eluvio.slack.com/archives/CF7AQGUH0/p1646078353729379)
So we made a 'site map' section that points to everything in the site and let the 'titles', 'series', 'clips' be lists that the user can manage independently
-SS

Example format:
```{
  commit: {...},
  public: {...},
  site_map: {
    searchables: {
      ITEMONE: {
        .: {
            auto_update: {
              tag: "latest"
            },
            container: "hq__anotherhash..."
          },
        /: "/qfab/hq__abc123.../meta/searchables"
      }
    }
  }
  ```

### Usage

1. To configure, click on desired content object. Note, the object must be configured to use Asset Manager as the Manage App, which is set on the object itself or the content type.
2. Click on the Gear icon on the upper left-hand side. This will open the spec form (shown below).

![image](https://user-images.githubusercontent.com/91760982/170564052-aa739c52-7367-4006-8031-a902f1f900c0.png)

4. Check the setting labeled Show Searchables Tab.
5. Click on Save Spec button.
6. You should now see a Searchables tab within Asset Manager.

![image](https://user-images.githubusercontent.com/91760982/170564642-f1e1f765-7dd0-49da-ac9a-eacdfc34e279.png)

Please also refer to https://github.com/eluv-io/elv-asset-manager/pull/10 for testing notes regarding changes.

**Comment by elv-serban** [comment]
Notes 2022-12-07

Searchables
- add multiple items and save - only one item gets added and the rest discarded
- ability to do multi-select

Index Configuration
- `Paths` field - focus goes away after typing one character (dv3)

**Comment by elv-zenia** [comment]
Additional notes from SS 12/7/22:
- might be good to only enable the histogram checkbox in the app for the kind of field that works [`text` vs `string`]
- my Indexer Config App doesn't seem to save correctly - looks like it reverts to the previous metadata after save.
- And also thirdly - let's call that tab "Search" (instead of "Indexer Configuration")

**Comment by elv-zenia** [comment]
Fixes above https://github.com/eluv-io/elv-asset-manager/pull/10/commits/050f5250f53d65c2151076995f5a9d57f26a16c4

**Comment by elv-zenia** [comment]
Searchables ready to test in Asset Manager on demo.

**Comment by elv-gerald** [comment]
I found a copy text bug when viewing searches in the asset manager. In the list of searchables if I highlight a content hash to copy with: 

- right click copy, it copies the content hash as expected
- cmd+c, I actually copy an unrelated url instead of the hash. Here is an example: https://core.demov3.contentfabric.io/#/apps/Eluvio%20Fabric%20Browser/#/content/ilib3ErteXJcCoTapj2ZhEvMKWau6jET/iq__43p9x5vGFPpZhagPLeFSd1dopocm/edit
![Screenshot 2023-03-29 at 3 01 54 PM](https://user-images.githubusercontent.com/79117605/228678195-31677169-1b23-4fe6-8848-480c0a8a43eb.png)

**Comment by elv-gerald** [comment]
I found a bug. The app throws an error when I try to add an object using its hash or content ID rather than selecting with the UI. Here is an example video where I try to add the content with its hash but it fails and the same content works when I just select it. 


https://user-images.githubusercontent.com/79117605/228689734-4d767b8e-32ab-4c8f-ac6c-8ccabf64cb18.mov

**Comment by elv-zenia** [comment]
> I found a copy text bug when viewing searchables in the asset manager. In the list of searchables if I highlight a content hash to copy with:
> 
> * right click copy, it copies the content hash as expected
> * cmd+c, I actually copy an unrelated url instead of the hash. Here is an example: https://core.demov3.contentfabric.io/#/apps/Eluvio%20Fabric%20Browser/#/content/ilib3ErteXJcCoTapj2ZhEvMKWau6jET/iq__43p9x5vGFPpZhagPLeFSd1dopocm/edit
>   ![Screenshot 2023-03-29 at 3 01 54 PM](https://user-images.githubusercontent.com/79117605/228678195-31677169-1b23-4fe6-8848-480c0a8a43eb.png)

Which browser do you see this behavior in? Is it consistent? I'm having trouble reproducing.

**Comment by elv-gerald** [comment]
> Which browser do you see this behavior in? Is it consistent? I'm having trouble reproducing.
It was happening on brave but I just updated it and now its not happening. I also double checked firefox and that works good too. 

We are good. It was probably a browser thing that got fixed after it updated.

**Comment by elv-zenia** [comment]
Adding an object by object id/version hash with the search box fixed by https://github.com/eluv-io/elv-asset-manager/pull/10/commits/f773f49676e549ee5486e8c5f18fa7b0494e88b0. Deployed to demo. @elv-gerald

**Comment by elv-zenia** [comment]
Deployed to prod.
