### ISSUE TITLE
Downloading a part automatically adds a 'txt' extension

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-fabric-browser#36]
Admittedly only a minor annoyance, but if easy to prevent this would be helpful.

Seen on Chrome - OS X

Click on an object, click Show Parts, and click Download for a part

Expected: file is downloaded without extension

Actual: filename has `.txt` added, e.g. `hqpeJGiz97uBRxcbS2SyUeDSARwtZpwtmPLvp47gbjkk2v6Z23bv.txt`

(In mezzanine objects most of the parts are actually playable as MP4 files, but AFAIK we have no way in fabric to associate a mime type with a particular part)

**Comment by elv-zenia** [comment]
After investigating, this seems to be a known Chrome issue with mime type mapping. A possible workaround is saving the file as a binary type, such as application/octet-stream, which saves the file without a file extension in Chrome. However, I'm not sure what the upload implications would be.
Related: 
- https://bugs.chromium.org/p/chromium/issues/detail?id=38213
- `GetContentTypeFromFileName` https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/fileapi/file.cc;l=64;bpv=0;bpt=1
- Addresses sniffing behavior https://bugs.chromium.org/p/chromium/issues/detail?id=106150

**Comment by eponymous301** [comment]
Ah, I did notice the other day that Safari does not add the .txt extension. If problematic to fix for Chrome, not worth the effort IMO.

**Comment by elv-zenia** [comment]
Agreed. Closing this for now.
