### ISSUE TITLE
After changing permission via command line, 'Publicly Listable ' object showed permission 'Viewable' until relogin/acct switch

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-fabric-browser#41]
Perhaps issue is that the refresh icon next to search box does not retrieve all changes to object permissions? Or cache check does not check for visibility change?

Not critical, but did lead me on a wild goose chase for a while.

Replication: (demo network, OS X chrome and safari)

 * Ingest media object
 * Set object permission to Editable
 * Log in to fabric browser, go to the newly ingested object
 * Object shows 'Permissions: Editable'
 * From command line, using the ingest user's key, set object permission to 'listable'
 * In fabric browser hit refresh icon next to search button
 
Expected: Value displayed for 'Permissions:' changes to 'Publicly Listable'

Actual: Value displayed changes to `Viewable' and remains so after clicking multiple times on refresh icon

Permission displayed stayed at `Viewable` indefinitely, even after navigating to a different object and back (object info cached?).

To get actual value 'Publicly Listable' to display, it was necessary to either do a full browser reload to force re-login, or switch to a different user account and back.

**Comment by elv-arun** [comment]
verfied.
