### ISSUE TITLE
Add simple ingest page

### ISSUE THREAD

**Issue by elv-zenia** [eluv-io/elv-fabric-browser#45]
Add ingest option to libraries that are set up with both a mezzanine content type and default ABR profile as well as to an object.

https://github.com/eluv-io/elv-fabric-browser/pull/40

**Comment by elv-gerald** [comment]
Tested and verified on testv4.
I ingest media with both short (1 min) and longer (10+ min) content.  Tested the following scenarios with each type of content
- drm
- clear
- both
- create new media object
- convert existing object

testv4 is going through alot of changes right now and it would be best to test this on demov3.

**Comment by elv-zenia** [comment]
Ingest app within Fabric Browser has been removed in favor of Core Media Ingest.
Changes that disable ingest actions: https://github.com/eluv-io/elv-fabric-browser/commit/38ee317d77cac682d9a80e1d4606197c46477508
