### ISSUE TITLE
Object copy fixup

### ISSUE THREAD

**Issue by elv-serban** [eluv-io/elv-fabric-browser#67]
A few changes for the object copy flow:

1. Target object should be private (visibility 0)
2. When adding a new encryption key use type `User` (currently type says `Creator`)

**Comment by elv-zenia** [comment]
@elv-arun Ready to verify.

**Comment by elv-gerald** [comment]
Verified. I tested with several objects that visibility is 0 and added encryption keys are of types user. I tested with 1 and several keys as well. 

Copy with just  owner
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/79117605/227654335-e0b23b79-d1f3-4b40-8dc6-e7d6afdf0642.png">

Copy with owner and user
<img width="1043" alt="image" src="https://user-images.githubusercontent.com/79117605/227654371-d638b794-4cc5-43e1-96b8-89be7e21f9fe.png">

Copy with owner and more than 1 user
<img width="1150" alt="image" src="https://user-images.githubusercontent.com/79117605/227654395-0a3ffc73-99c4-4261-9014-d62d6ffb970e.png">

Visibility is 0
<img width="792" alt="image" src="https://user-images.githubusercontent.com/79117605/227654426-0926fdb3-9d58-4226-961d-a94b72f0d881.png">
