### ISSUE TITLE
Suggestion: nicer error message when trying to view deleted object

### ISSUE THREAD

**Issue by eponymous301** [eluv-io/elv-fabric-browser#79]
Current error looks like: `Error: call exception (address="0xaaf38f52c4c5ba331bcbdd2a6a6fb7fc60f73863", method="countVersionHashes()", args=[], version=4.0.49)`

Nicer would be something like: "Could not determine version count - object may have been deleted, or you may not have permission to access"

If it is actually possible for fabric browser to distinguish between the two scenarios (deleted vs. insufficient permissions) then show the more specific error message.

**Comment by elv-zenia** [comment]
Deployed to prod.
