### ISSUE TITLE
Copy/clone an object into same library, different library

### ISSUE THREAD

**Issue by elv-arun** [eluv-io/elv-fabric-browser#8]
Epic: https://github.com/qluvio/info/issues/362

Small Features:
Item #1. Copy/clone an object into same library, different library

## Objective

Clone an object into 'my own' library.  This is the simplest type of clone where the target object is created by the owner of the source object.

## Proposal

Here is how I am envisioning it:

- Copy (or Clone (?) ) button
  - Alternatively we can connect the clone flow when creating a new object "Contribute"
    (I am also considering renaming "Contribute" to "Create" - I'm not sure how we kept Contribute for so long :) )
- Specify the destination library 
- Display a few fields that the user could change (if we don't change the name or description of the object, after we create the clone we can't tell which object is the old and which is the new)
   - I would say just 'name' and 'description' (/public/name and /public/description)
   - Pre-fill with the source name and description

**Comment by elv-zenia** [comment]
@elv-arun Ready for review.

**Comment by elv-serban** [comment]
To test - I believe this is still a problem:
- object owned by user A
   - has video with DRM
- edit rights to content admins group which contains user A and user B
- user B clones the object

New object doesn't work right due to something going on with the CAPS

**Comment by elv-zenia** [comment]
Above issue fixed. @elv-serban @elv-arun @elv-marc

**Comment by elv-serban** [comment]
Verified
